import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :party_line, PartyLineWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "9pIU5o1h7c3q7C/fHgf3yNTAub11gNB5S59xVYJkXL6SS1dPYQcgJc5wO/izdhXC",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:party_line, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:party_line, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :party_line, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# room transcripts as JSONL (flight recorder + future LoRA eval corpus)
config :party_line, :transcript_dir, "transcripts"

# the live dev playground hosts every room with the Operator on
config :party_line, :operator, enabled: true

# live memory: locally built deciduous API daemon (scripts/memory_daemon.sh)
token_path = Path.expand("~/.party_line/api-token")

if File.exists?(token_path) do
  config :party_line, :memory,
    enabled: true,
    api_url: "http://127.0.0.1:4141",
    token: token_path |> File.read!() |> String.trim(),
    root_graph: "party-line-root"
end

# the exchange's programmed lines (the switchboard view joins all of them)
config :party_line, :lines, [
  {"room-default", "whether cities are accidentally breeding smarter raccoons"},
  {"room-supper-club", "street food worth fighting a seagull for"},
  {"room-observatory", "what's actually up there tonight, no equipment required"}
]

# Postgres: the durable store behind the boards/clip ETS caches. Local brew
# postgres runs trust-auth for the current OS user with no password.
config :party_line, PartyLine.Repo,
  username: System.get_env("PGUSER") || System.get_env("USER") || "postgres",
  password: System.get_env("PGPASSWORD") || "",
  hostname: System.get_env("PGHOST") || "localhost",
  database: "party_line_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# board-life engine on in dev (off by default): bots post, comment, and vote
config :party_line, :boards_life, enabled: true

# atproto OAuth in dev: pin the base to the loopback IP, not "localhost".
#
# The loopback client's redirect_uri MUST be 127.0.0.1 (auth servers reject the
# "localhost" hostname), and the callback correlates the flow through a signed
# cookie. Browsers treat localhost and 127.0.0.1 as different hosts for
# cookies, so a base of http://localhost:4000 sets the cookie on one origin and
# gets redirected to the other — the cookie never comes back and the sign-in
# dies as "your sign-in expired". Same host everywhere, no mystery.
config :party_line, :atproto, base_url: "http://127.0.0.1:4000"
